// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: api/models/snapshot.proto

package snapshot_v1

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Snapshot_SensorState int32

const (
	Snapshot_NORMAL  Snapshot_SensorState = 0
	Snapshot_WARNING Snapshot_SensorState = 1
)

// Enum value maps for Snapshot_SensorState.
var (
	Snapshot_SensorState_name = map[int32]string{
		0: "NORMAL",
		1: "WARNING",
	}
	Snapshot_SensorState_value = map[string]int32{
		"NORMAL":  0,
		"WARNING": 1,
	}
)

func (x Snapshot_SensorState) Enum() *Snapshot_SensorState {
	p := new(Snapshot_SensorState)
	*p = x
	return p
}

func (x Snapshot_SensorState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Snapshot_SensorState) Descriptor() protoreflect.EnumDescriptor {
	return file_api_models_snapshot_proto_enumTypes[0].Descriptor()
}

func (Snapshot_SensorState) Type() protoreflect.EnumType {
	return &file_api_models_snapshot_proto_enumTypes[0]
}

func (x Snapshot_SensorState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Snapshot_SensorState.Descriptor instead.
func (Snapshot_SensorState) EnumDescriptor() ([]byte, []int) {
	return file_api_models_snapshot_proto_rawDescGZIP(), []int{0, 0}
}

type Snapshot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SnapshotId string               `protobuf:"bytes,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	SensorId   string               `protobuf:"bytes,2,opt,name=sensor_id,json=sensorId,proto3" json:"sensor_id,omitempty"`
	SensorName string               `protobuf:"bytes,3,opt,name=sensor_name,json=sensorName,proto3" json:"sensor_name,omitempty"`
	State      Snapshot_SensorState `protobuf:"varint,4,opt,name=state,proto3,enum=watercontrol.models.Snapshot_SensorState" json:"state,omitempty"`
	Timestamp  *timestamp.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_models_snapshot_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_api_models_snapshot_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_api_models_snapshot_proto_rawDescGZIP(), []int{0}
}

func (x *Snapshot) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *Snapshot) GetSensorId() string {
	if x != nil {
		return x.SensorId
	}
	return ""
}

func (x *Snapshot) GetSensorName() string {
	if x != nil {
		return x.SensorName
	}
	return ""
}

func (x *Snapshot) GetState() Snapshot_SensorState {
	if x != nil {
		return x.State
	}
	return Snapshot_NORMAL
}

func (x *Snapshot) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_api_models_snapshot_proto protoreflect.FileDescriptor

var file_api_models_snapshot_proto_rawDesc = []byte{
	0x0a, 0x19, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x73, 0x6e, 0x61,
	0x70, 0x73, 0x68, 0x6f, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x77, 0x61, 0x74,
	0x65, 0x72, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73,
	0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x8c, 0x02, 0x0a, 0x08, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x12, 0x1f,
	0x0a, 0x0b, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x49, 0x64, 0x12,
	0x1b, 0x0a, 0x09, 0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b,
	0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x3f, 0x0a,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x29, 0x2e, 0x77,
	0x61, 0x74, 0x65, 0x72, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x73, 0x2e, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x2e, 0x53, 0x65, 0x6e, 0x73,
	0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x38,
	0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x26, 0x0a, 0x0b, 0x53, 0x65, 0x6e, 0x73,
	0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x4f, 0x52, 0x4d, 0x41,
	0x4c, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x57, 0x41, 0x52, 0x4e, 0x49, 0x4e, 0x47, 0x10, 0x01,
	0x42, 0x3e, 0x5a, 0x3c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66,
	0x30, 0x72, 0x6d, 0x75, 0x6c, 0x2f, 0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x2d, 0x63, 0x6f, 0x6e,
	0x74, 0x72, 0x6f, 0x6c, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f,
	0x74, 0x5f, 0x76, 0x31, 0x3b, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x5f, 0x76, 0x31,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_models_snapshot_proto_rawDescOnce sync.Once
	file_api_models_snapshot_proto_rawDescData = file_api_models_snapshot_proto_rawDesc
)

func file_api_models_snapshot_proto_rawDescGZIP() []byte {
	file_api_models_snapshot_proto_rawDescOnce.Do(func() {
		file_api_models_snapshot_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_models_snapshot_proto_rawDescData)
	})
	return file_api_models_snapshot_proto_rawDescData
}

var file_api_models_snapshot_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_models_snapshot_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_models_snapshot_proto_goTypes = []interface{}{
	(Snapshot_SensorState)(0),   // 0: watercontrol.models.Snapshot.SensorState
	(*Snapshot)(nil),            // 1: watercontrol.models.Snapshot
	(*timestamp.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_api_models_snapshot_proto_depIdxs = []int32{
	0, // 0: watercontrol.models.Snapshot.state:type_name -> watercontrol.models.Snapshot.SensorState
	2, // 1: watercontrol.models.Snapshot.timestamp:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_models_snapshot_proto_init() }
func file_api_models_snapshot_proto_init() {
	if File_api_models_snapshot_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_models_snapshot_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Snapshot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_models_snapshot_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_models_snapshot_proto_goTypes,
		DependencyIndexes: file_api_models_snapshot_proto_depIdxs,
		EnumInfos:         file_api_models_snapshot_proto_enumTypes,
		MessageInfos:      file_api_models_snapshot_proto_msgTypes,
	}.Build()
	File_api_models_snapshot_proto = out.File
	file_api_models_snapshot_proto_rawDesc = nil
	file_api_models_snapshot_proto_goTypes = nil
	file_api_models_snapshot_proto_depIdxs = nil
}
